### ISSUE TITLE
clean up npm ownership and publish a new hashlib version with issue #16 fix

### ISSUE THREAD

**Issue by trentm** [brainpicture/hashlib#20]
Illarionov,

Could you increment the hashlib version (in package.json, e.g. to "1.0.1") and publish a new version of hashlib, please? I need a new release with the fix for issue #16 (build fix for solaris/smartos from Ryan) to be able to use "hashlib" in my own node.js project's "package.json" file.

From reading `npm info hashlib` and speaking with @isaacs, my understanding is that _isaacs_ published "hashlib" to the npm registry. Isaac would be fine cleaning up ownership of "hashlib" in the npm registry so that you're the owner. First you'd need to create an user account with the npm registry via `npm adduser` and then pass your npm username on to Isaac to clean up. I can help co-ordinate that, if that would help.

Thanks,
Trent

**Comment by trentm** [comment]
note that I published a trentm-hashlib 1.0.1 to npm until you're able to publish a new hashlib.

**Comment by brainpicture** [comment]
Sorry for the late answer, was too busy last week. Already send email to
Isaac.

Regards,
Oleg Illarionov (Олег Илларионов)
icq         816969
jabber     oleg@emby.ru
email      oleg@emby.ru
skype     webmovement

**Comment by isaacs** [comment]
Should be resolved now, thanks Oleg. (This was the last "admin party" module that I'd had to take ownership of, so it's nice to finally have that all cleared up!)

**Comment by brainpicture** [comment]
Thanks very much =)

Regards,
Oleg Illarionov (Олег Илларионов)
icq         816969
jabber     oleg@emby.ru
email      oleg@emby.ru
